doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
autodetect: yes
ignore-paths:
    - docs
ignore-patterns:
    - (^|/)docs(/|$)

mccabe:
  disable:
    - MC0001

pep8:
  disable:
    - N803
    - N802
    - N806

pylint:
  disable:
    - star-args
  options:
    include-naming-hint: yes
    function-rgx: "[a-z_][a-zA-Z0-9_]{2,30}$"
    function-name-hint: "[a-z_][a-zA-Z0-9_]{2,30}$"
    variable-rgx: "[a-z_][a-zA-Z0-9_]{1,30}$"
    variable-name-hint: "[a-z_][a-zA-Z0-9_]{1,30}$"
    attr-rgx: "[a-z_][a-zA-Z0-9_]{1,30}$"
    attr-name-hint: "[a-z_][a-zA-Z0-9_]{1,30}$"
    argument-rgx: "[a-z_][a-zA-Z0-9_]{1,30}$"
    argument-name-hint: "[a-z_][a-zA-Z0-9_]{1,30}$"
    method-rgx: "[a-z_][a-zA-Z0-9_]{1,30}$"
    method-name-hint: "[a-z_][a-zA-Z0-9_]{1,30}$"
    max-module-lines: 2500
    max-locals: 15
    max-attributes: 7
    min-public-methods: 0
